### ISSUE TITLE
Non-merged PR's count towards the goal

### ISSUE THREAD

**Issue by DirtySoc** [jenkoian/hacktoberfest-checker#374] opened 2019-10-03 00:38 UTC
![image](https://user-images.githubusercontent.com/33207400/66091153-9d43f180-e554-11e9-86a3-961e87e8cdfd.png)

**Comment by Pedro-Mendes** [comment] 2019-10-03 01:19
Not a bug. Hacktoberfest doesn't care if the PR is merged or not to give away the prizes.

**Closed** 2019-10-03 01:27 UTC
